### ISSUE TITLE
WINDOWS使用RaiDrive挂载，显示云盘大小有7.99EP。。。

### ISSUE THREAD

**Issue by cklx0719** [MaRuifu/ali-webdav#1]
这个值肯定是不准确的，显示的是物理空间？
![image](https://user-images.githubusercontent.com/25605487/129820050-2343c3e1-17f6-4916-aca7-18773cca865a.png)

**Comment by MaRuifu** [comment]
是的显示的不准，这个应该是阿里的硬盘池，显示的不是个人的，不过当你超过自己的大小的时候 不会上传上去了。
