### ISSUE TITLE
java -jar ali-webdav-0.1.0.jar 的方式会报错

### ISSUE THREAD

**Issue by adinghub** [MaRuifu/ali-webdav#2]
当我使用  `java -jar ali-webdav-0.1.0.jar  --aliyundrive.refresh-token="12ecb25e6ef23f0baf6bc3f9221022c7"  --server.port="8888"` 的时候，会报错 ` Error creating bean with name 'aliYunDriverClientService' defined in URL [jar:file:/D:/Program%20Files/ali-webdav-server-0.1.0/ali-webdav-0.1.0.jar!/BOOT-INF/classes!/com/github/maruifu/webdav/store/AliYunDriverClientService.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'teambitionClient' defined in class path resource [com/github/maruifu/webdav/config/AliYunDriverAutoConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.github.maruifu.webdav.client.AliYunDriverClient]: Factory method 'teambitionClient' threw exception; nested exception is net.sf.webdav.exceptions.WebdavException: okhttp3.internal.http2.ConnectionShutdownException`

**Comment by MaRuifu** [comment]
12ecb25e6ef23f0baf6bc3f9221022c7 这个是 是我的token  需要换成你的token
请阅读 [https://github.com/MaRuifu/ali-webdav/blob/main/tutorial/getToken.md](https://github.com/MaRuifu/ali-webdav/blob/main/tutorial/getToken.md)
